Fix licensing information to align with legal terms
canonical/anbox-cloud.io pull request #338
Opened 2024-06-14 09:45 UTC by keirthana

## Done

For documenration, updated license information to CC-BY-SA according to terms confirmed with legal team.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8043/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[if relevant, include a screenshot]

2024-06-14 09:45 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://anbox-cloud-io-338.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/373)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-06-14 17:25 UTC, edlerd requested changes
The copyright now spans two lines, breaking within the license name:

![image](https://github.com/canonical/anbox-cloud.io/assets/1155472/38f7853a-60fd-42dc-a134-615b1fae618d)

Maybe we can rearrange the text a bit like this:

![image](https://github.com/canonical/anbox-cloud.io/assets/1155472/ad8f10ee-7bfc-4ac8-a185-49e174fe8a96)

Not sure how flexible the text is legally. Or add a line break after the year, that improves as well:

![image](https://github.com/canonical/anbox-cloud.io/assets/1155472/bd7ae244-0098-4c87-85cb-5445355e6c66)

2024-06-18 05:08 UTC, keirthana commented
> The copyright now spans two lines, breaking within the license name:
> 
> ![image](https://private-user-images.githubusercontent.com/1155472/339851828-38f7853a-60fd-42dc-a134-615b1fae618d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODczMTAsIm5iZiI6MTcxODY4NzAxMCwicGF0aCI6Ii8xMTU1NDcyLzMzOTg1MTgyOC0zOGY3ODUzYS02MGZkLTQyZGMtYTEzNC02MTViMWZhZTYxOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDUwMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWZlZmYxNjk4ZDMxODUyMjUxZDEwZWRlM2Q5MjFkYWZhN2QzNGYzOWIzZGIzY2I1ODc2MTdhNzkxZDdjYTQ2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Acl3niG1ZQT60MKmfurhmtYQ8aMTctswBIRz5v4jrJ4)
> 
> Maybe we can rearrange the text a bit like this:
> 
> ![image](https://private-user-images.githubusercontent.com/1155472/339852233-ad8f10ee-7bfc-4ac8-a185-49e174fe8a96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODczMTAsIm5iZiI6MTcxODY4NzAxMCwicGF0aCI6Ii8xMTU1NDcyLzMzOTg1MjIzMy1hZDhmMTBlZS03YmZjLTRhYzgtYTE4NS00OWUxNzRmZThhOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDUwMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2QzMjljNDRmMzZhZmY2OTlmOTllY2Y3MzMwZTFkMjA4MzVhMTJhYTA1MzUwNDgwMjE2OTFmNDMwZWRjNGZjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dMMzf7zTwWbHyDnqW2yPXchJVL3U_nT2K_BdSMRa3Mc)
> 
> Not sure how flexible the text is legally. Or add a line break after the year, that improves as well:
> 
> ![image](https://private-user-images.githubusercontent.com/1155472/339852474-bd7ae244-0098-4c87-85cb-5445355e6c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODczMTAsIm5iZiI6MTcxODY4NzAxMCwicGF0aCI6Ii8xMTU1NDcyLzMzOTg1MjQ3NC1iZDdhZTI0NC0wMDk4LTRjODctODVjYi01NDQ1MzU1ZTZjNjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDUwMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzI4M2ZmOTYxZDc5YjA5ZTQ5NDY3YTQzNjEyMzQ3NzI3NmQyMWY5YzQzNGNhZWMxYTdlZjE2NTViNzA1N2JjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-hzRvcG_YxE-KeT-K0-UzRb2INqieGo0jFBa2hV5e0o)

I was trying to see if I can make the footer content two column instead of three. However, this is better. I have chosen the latter option so that we keep the text intact.

2024-06-18 07:19 UTC, edlerd approved these changes

2024-06-18 07:19 UTC, merged